#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 5
#SBATCH --time 00:30:00
#SBATCH --gres gpu:1
#SBATCH --partition gpu
#SBATCH --reservation COMS30005GPU
#SBATCH --account COMS30005
#SBATCH --output d2q9-bgk.out
#SBATCH --exclusive


echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

#! Run the executable
srun ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# srun ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# srun ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
